### ISSUE TITLE
Basic SDK - adding field diagnosisUrl to StatusResponse 

### ISSUE THREAD

**Issue by ddobryakredknee** [rango-exchange/rango-types#27]
According to documentation StatusResponse should contains field diagnosisUrl (https://docs.rango.exchange/integration-quick-start/check-status). If so please update:
https://github.com/rango-exchange/rango-types/blob/4b93a8570a7b1850864e49882522a7c07d4d2a43/src/api/basic/transactions.ts#L145 like this:
```
export type StatusResponse = {
  status: TransactionStatus | null
  error: string | null
  diagnosisUrl: string | null
  output: StatusOutput | null
  explorerUrl: SwapExplorerUrl[] | null
  bridgeData: BridgeData | null
}
```

**Comment by RanGojo** [comment]
Thanks for reporting. Fixed https://github.com/rango-exchange/rango-types/commit/a9bfefa4b9687ed69d66d1b4f3c08b1828611408
